module.exports={
    pages:{
        login:{
            entry:'src/login.js',
            template:'public/login.html'
        },
        index:{
            entry:'src/main.js',
            template:'public/index.html',
        }
    }
}
